site:
  title:  Overview on CVE and Tools Used
  start_page: sustaining-eng-workflow-test::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

content:
  sources:
  - url: ./

asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
